#!/usr/bin/env python
"""Build SQL chunks that preserve workbook cells in public.ll_source_cells.

The generated SQL is intentionally limited to public.ll_* objects. It does not
read from or mutate any existing non-ll_* Supabase table.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_EXTRACT = ROOT / "qa-artifacts" / "source-diff" / "xlsx-extract.json"
DEFAULT_OUT = ROOT / "qa-artifacts" / "supabase" / "source-cell-sql"


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def chunks(rows: List[Dict[str, Any]], size: int) -> Iterable[List[Dict[str, Any]]]:
    for index in range(0, len(rows), size):
        yield rows[index : index + size]


def normalize_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def read_extract(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def build_import_id(extract: Dict[str, Any]) -> str:
    source_name = normalize_text(extract.get("source_name", "source"))
    source_hash = normalize_text(extract.get("summary", {}).get("non_empty_cell_count", "0"))
    generated = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    digest = hashlib.sha256(source_name.encode("utf-8")).hexdigest()[:12]
    return f"xlsx_260414_logistics_leasing_{source_hash}_{digest}_{generated}"


def schema_sql() -> str:
    return """
begin;

create table if not exists public.ll_source_cells (
  source_cell_id text primary key,
  import_id text not null references public.ll_import_runs(import_id) on delete cascade,
  source_type text not null default 'xlsx',
  source_name text not null,
  sheet_name text not null,
  row_number integer not null,
  column_number integer not null,
  column_letter text not null,
  header_row_number integer,
  header_label text,
  a1_ref text not null,
  raw_value_text text,
  display_value_text text,
  formula_text text,
  value_type text,
  is_blank boolean not null default false,
  row_hash text,
  cell_hash text not null,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (import_id, sheet_name, row_number, column_number)
);

create index if not exists ll_source_cells_import_sheet_idx
  on public.ll_source_cells(import_id, sheet_name, row_number);
create index if not exists ll_source_cells_sheet_header_idx
  on public.ll_source_cells(sheet_name, header_label);
create index if not exists ll_source_cells_blank_idx
  on public.ll_source_cells(import_id, is_blank);

alter table public.ll_source_cells enable row level security;

create table if not exists public.ll_data_quality_findings (
  finding_id text primary key,
  audit_run_id text,
  finding_type text not null,
  severity text not null default 'warning',
  entity_type text,
  entity_id text,
  source_sheet_name text,
  source_row_number integer,
  source_column_number integer,
  source_header text,
  source_value_text text,
  supabase_value_text text,
  status text not null default 'open',
  finding_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ll_data_quality_findings_type_idx
  on public.ll_data_quality_findings(finding_type, status);
create index if not exists ll_data_quality_findings_source_idx
  on public.ll_data_quality_findings(source_sheet_name, source_row_number);

alter table public.ll_data_quality_findings enable row level security;

commit;
""".strip()


def import_run_sql(import_id: str, extract: Dict[str, Any]) -> str:
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    summary = extract.get("summary", {})
    source_name = normalize_text(extract.get("source_name", ""))
    return f"""
insert into public.ll_import_runs (
  import_id, source_type, source_name, file_name, started_at, finished_at,
  status, row_counts, memo
) values (
  {sql_quote(import_id)},
  'xlsx',
  {sql_quote(source_name)},
  {sql_quote(source_name)},
  {sql_quote(now)}::timestamptz,
  {sql_quote(now)}::timestamptz,
  'prepared',
  {sql_quote(json.dumps(summary, ensure_ascii=False, sort_keys=True))}::jsonb,
  'Excel source cell preservation import generated by scripts/data/build-source-cell-sql.py'
)
on conflict (import_id) do update set
  finished_at = excluded.finished_at,
  status = excluded.status,
  row_counts = excluded.row_counts,
  memo = excluded.memo;
""".strip()


def records_for_cells(import_id: str, extract: Dict[str, Any]) -> List[Dict[str, Any]]:
    source_name = normalize_text(extract.get("source_name", ""))
    sheets = {sheet["sheet_name"]: sheet for sheet in extract.get("sheets", [])}
    rows_by_id = {row["row_id"]: row for row in extract.get("rows", [])}
    records: List[Dict[str, Any]] = []
    for cell in extract.get("cells", []):
        sheet = sheets.get(cell.get("sheet_name"), {})
        row = rows_by_id.get(cell.get("row_id"), {})
        payload = {
            "a1_ref": cell.get("a1_ref"),
            "note": cell.get("note"),
            "number_format": cell.get("number_format"),
            "source_hash": cell.get("source_hash"),
        }
        records.append(
            {
                "source_cell_id": f"{import_id}:{cell['cell_id']}",
                "import_id": import_id,
                "source_type": "xlsx",
                "source_name": source_name,
                "sheet_name": cell.get("sheet_name", ""),
                "row_number": int(cell.get("row_number", 0)),
                "column_number": int(cell.get("column_index", 0)),
                "column_letter": cell.get("column_letter", ""),
                "header_row_number": int(sheet.get("header_row", 0)) if sheet.get("header_row") else None,
                "header_label": cell.get("header_label", ""),
                "a1_ref": cell.get("a1_ref", ""),
                "raw_value_text": normalize_text(cell.get("raw_value")),
                "display_value_text": normalize_text(cell.get("display_value")),
                "formula_text": normalize_text(cell.get("formula")),
                "value_type": cell.get("value_type", ""),
                "is_blank": bool(cell.get("is_blank")),
                "row_hash": row.get("row_hash", ""),
                "cell_hash": cell.get("source_hash", ""),
                "source_payload": payload,
            }
        )
    return records


def insert_sql(records: List[Dict[str, Any]]) -> str:
    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    return f"""
insert into public.ll_source_cells (
  source_cell_id, import_id, source_type, source_name, sheet_name,
  row_number, column_number, column_letter, header_row_number, header_label,
  a1_ref, raw_value_text, display_value_text, formula_text, value_type,
  is_blank, row_hash, cell_hash, source_payload
)
select
  source_cell_id, import_id, source_type, source_name, sheet_name,
  row_number, column_number, column_letter, header_row_number, header_label,
  a1_ref, raw_value_text, display_value_text, formula_text, value_type,
  is_blank, row_hash, cell_hash, source_payload
from jsonb_to_recordset($${payload}$$::jsonb) as x(
  source_cell_id text,
  import_id text,
  source_type text,
  source_name text,
  sheet_name text,
  row_number integer,
  column_number integer,
  column_letter text,
  header_row_number integer,
  header_label text,
  a1_ref text,
  raw_value_text text,
  display_value_text text,
  formula_text text,
  value_type text,
  is_blank boolean,
  row_hash text,
  cell_hash text,
  source_payload jsonb
)
on conflict (source_cell_id) do update set
  raw_value_text = excluded.raw_value_text,
  display_value_text = excluded.display_value_text,
  formula_text = excluded.formula_text,
  value_type = excluded.value_type,
  is_blank = excluded.is_blank,
  row_hash = excluded.row_hash,
  cell_hash = excluded.cell_hash,
  source_payload = excluded.source_payload,
  updated_at = now();
""".strip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--extract", default=str(DEFAULT_EXTRACT))
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT))
    parser.add_argument("--chunk-size", type=int, default=500)
    args = parser.parse_args()

    extract_path = Path(args.extract)
    if not extract_path.is_absolute():
        extract_path = ROOT / extract_path
    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = ROOT / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    extract = read_extract(extract_path)
    import_id = build_import_id(extract)
    records = records_for_cells(import_id, extract)

    (out_dir / "00_schema.sql").write_text(schema_sql() + "\n", encoding="utf-8")
    (out_dir / "01_import_run.sql").write_text(import_run_sql(import_id, extract) + "\n", encoding="utf-8")
    for idx, chunk in enumerate(chunks(records, args.chunk_size), start=1):
        (out_dir / f"{idx + 1:02d}_source_cells_{idx:03d}.sql").write_text(insert_sql(chunk) + "\n", encoding="utf-8")

    summary = {
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "extract": str(extract_path),
        "out_dir": str(out_dir),
        "import_id": import_id,
        "source_cell_rows": len(records),
        "non_empty_cell_rows": sum(1 for row in records if not row["is_blank"]),
        "chunk_size": args.chunk_size,
        "chunk_count": (len(records) + args.chunk_size - 1) // args.chunk_size,
        "scope_guard": "Only public.ll_* tables are created or written.",
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
